// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttfylrdftphnluaanpnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZnlscmRmdHBobmx1YWFucG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Mjg3NTgsImV4cCI6MjA3MTAwNDc1OH0.K2MV8_edzdp3M41rLSd3SdWRMH0sPzmwwQ3tiMRNIhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});